<?php

/**
 * Test_PluginSimpleRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Test_PluginSimpleRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Test_PluginSimpleRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Test_PluginSimpleRecord');
    }
}