<?php

/**
 * Test_PluginReferenceRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Test_PluginReferenceRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Test_PluginReferenceRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Test_PluginReferenceRecord');
    }
}