<?php

/**
 * Test_PluginSelfReferenceRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Test_PluginSelfReferenceRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Test_PluginSelfReferenceRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Test_PluginSelfReferenceRecord');
    }
}