all:
  ifx_dummy_connecton:
       class: sfDoctrineDatabase
       param:
         #dsn: 'informix:host=itools-informix32; service=3306;database=bfs;server=filmfest;protocol=onsoctcp;db_locale=de_DE.819;client_locale=de_DE.UTF8;'
         dsn: 'informix:host=itools-informix32; service=9088;database=ifx_test;server=itools;protocol=onsoctcp;'
         username: root
         password: